using SDLTooSharp.Bindings.SDL2;

namespace SDLTooSharp.Managed.Common.Events;

public enum EventType : uint
{
    Quit = SDL.SDL_EventType.SDL_QUIT,
    AppTerminating = SDL.SDL_EventType.SDL_APP_TERMINATING,
    AppLowMemory = SDL.SDL_EventType.SDL_APP_LOWMEMORY,
    AppWillEnterBackground = SDL.SDL_EventType.SDL_APP_WILLENTERBACKGROUND,
    AppDidEnterBackground = SDL.SDL_EventType.SDL_APP_DIDENTERBACKGROUND,
    AppWillEnterForeground = SDL.SDL_EventType.SDL_APP_WILLENTERFOREGROUND,
    AppDidEnterForeground = SDL.SDL_EventType.SDL_APP_DIDENTERFOREGROUND,
    LocaleChanged = SDL.SDL_EventType.SDL_LOCALECHANGED,
    DisplayEvent = SDL.SDL_EventType.SDL_DISPLAYEVENT,
    WindowEvent = SDL.SDL_EventType.SDL_WINDOWEVENT,
    SysWMEvent = SDL.SDL_EventType.SDL_SYSWMEVENT,
    KeyDown = SDL.SDL_EventType.SDL_KEYDOWN,
    KeyUp = SDL.SDL_EventType.SDL_KEYUP,
    TextEditing = SDL.SDL_EventType.SDL_TEXTEDITING,
    TextInput = SDL.SDL_EventType.SDL_TEXTINPUT,
    KeymapChanged = SDL.SDL_EventType.SDL_KEYMAPCHANGED,
    TextEditingExt = SDL.SDL_EventType.SDL_TEXTEDITING_EXT,
    MouseMotion = SDL.SDL_EventType.SDL_MOUSEMOTION,
    MouseButtonDown = SDL.SDL_EventType.SDL_MOUSEBUTTONDOWN,
    MouseButtonUp = SDL.SDL_EventType.SDL_MOUSEBUTTONUP,
    MouseWheel = SDL.SDL_EventType.SDL_MOUSEWHEEL,
    JoyAxisMotion = SDL.SDL_EventType.SDL_JOYAXISMOTION,
    JoyBallMotion = SDL.SDL_EventType.SDL_JOYBALLMOTION,
    JoyHatMotion = SDL.SDL_EventType.SDL_JOYHATMOTION,
    JoyButtonDown = SDL.SDL_EventType.SDL_JOYBUTTONDOWN,
    JoyButtonUp = SDL.SDL_EventType.SDL_JOYBUTTONUP,
    JoyDeviceAdded = SDL.SDL_EventType.SDL_JOYDEVICEADDED,
    JoyDeviceRemoved = SDL.SDL_EventType.SDL_JOYDEVICEREMOVED,
    JoyBatteryUpdated = SDL.SDL_EventType.SDL_JOYBATTERYUPDATED,
    ControllerAxisMotion = SDL.SDL_EventType.SDL_CONTROLLERAXISMOTION,
    ControllerButtonDown = SDL.SDL_EventType.SDL_CONTROLLERBUTTONDOWN,
    ControllerButtonUp = SDL.SDL_EventType.SDL_CONTROLLERBUTTONUP,
    ControllerDeviceAdded = SDL.SDL_EventType.SDL_CONTROLLERDEVICEADDED,
    ControllerDeviceRemoved = SDL.SDL_EventType.SDL_CONTROLLERDEVICEREMOVED,
    ControllerDeviceRemapped = SDL.SDL_EventType.SDL_CONTROLLERDEVICEREMAPPED,
    ControllerTouchPadDown = SDL.SDL_EventType.SDL_CONTROLLERTOUCHPADDOWN,
    ControllerTouchPadMotion = SDL.SDL_EventType.SDL_CONTROLLERTOUCHPADMOTION,
    ControllerTouchPadUp = SDL.SDL_EventType.SDL_CONTROLLERTOUCHPADUP,
    ControllerSensorUpdate = SDL.SDL_EventType.SDL_CONTROLLERSENSORUPDATE,
    FingerDown = SDL.SDL_EventType.SDL_FINGERDOWN,
    FingerUp = SDL.SDL_EventType.SDL_FINGERUP,
    FingerMotion = SDL.SDL_EventType.SDL_FINGERMOTION,
    DollarGesture = SDL.SDL_EventType.SDL_DOLLARGESTURE,
    DollarRecord = SDL.SDL_EventType.SDL_DOLLARRECORD,
    MultiGesture = SDL.SDL_EventType.SDL_MULTIGESTURE,
    ClipboardUpdate = SDL.SDL_EventType.SDL_CLIPBOARDUPDATE,
    DropFile = SDL.SDL_EventType.SDL_DROPFILE,
    DropText = SDL.SDL_EventType.SDL_DROPTEXT,
    DropBegin = SDL.SDL_EventType.SDL_DROPBEGIN,
    DropComplete = SDL.SDL_EventType.SDL_DROPCOMPLETE,
    AudioDeviceAdded = SDL.SDL_EventType.SDL_AUDIODEVICEADDED,
    AudioDeviceRemoved = SDL.SDL_EventType.SDL_AUDIODEVICEREMOVED,
    SensorUpdate = SDL.SDL_EventType.SDL_SENSORUPDATE,
    RenderTargetsReset = SDL.SDL_EventType.SDL_RENDER_TARGETS_RESET,
    RenderDeviceReset = SDL.SDL_EventType.SDL_RENDER_DEVICE_RESET,
    PollSentinel = SDL.SDL_EventType.SDL_POLLSENTINEL,
    UserEvent = SDL.SDL_EventType.SDL_USEREVENT,
}
